on:
  push:
    branches:
      - 'release/**'
    tags:
      - "v*.*.*"

jobs:
  build-installer:
    strategy:
      matrix:
        os: ['windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Determine Binary Name
        id: binary_name
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            echo "name=Eagle Eye-win.exe" >> $GITHUB_OUTPUT
          else
            echo "name=Eagle Eye-macos" >> $GITHUB_OUTPUT
          fi
        shell: bash
        
      - name: Build Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'eagle_eye.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: ${{ github.ref_type == 'tag' && steps.binary_name.outputs.name || '' }}
